version: '3.4'

volumes:
  db-data:
    driver: local

services:
  database:
    image: bitnami/postgresql:15
    container_name: 'storage-manager-pg-db'
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=storage_manager
    volumes:
      - 'db-data:/bitnami/postgresql'

  storagemanager.api:
    image: ${DOCKER_REGISTRY-}storagemanagerapi
    build:
      context: .
      dockerfile: StorageManager.API/Dockerfile
    depends_on:
      - database
    volumes:
      - .:/usr 
